# Generated by Django 4.1.6 on 2023-05-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
