# Generated by Django 4.1.6 on 2023-05-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_flight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeDeGoiaba',
            new_name='Quimica',
        ),
    ]
