# Generated by Django 4.1.6 on 2023-05-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_pedegoiaba_quimica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
