# Generated by Django 4.1.6 on 2023-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_quimica_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimica',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
