# Generated by Django 4.1.6 on 2023-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_quimica_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimica',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
