# Generated by Django 4.1.6 on 2023-05-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_quimica_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
