# Generated by Django 4.1.6 on 2023-05-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_quimica_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quimica',
            name='nome',
        ),
    ]
