# Generated by Django 4.1.6 on 2023-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_quimica_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimica',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='quimica',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quimica',
            name='valor',
            field=models.FloatField(),
        ),
    ]
