# Generated by Django 4.2 on 2023-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_quimica_nome_alter_quimica_id_alter_quimica_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimica',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
