# Generated by Django 4.2 on 2023-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_quimica_id_alter_quimica_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimica',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
