# Generated by Django 4.2 on 2023-05-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_quimica_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quimica',
            name='nome',
        ),
        migrations.AddField(
            model_name='quimica',
            name='peso',
            field=models.FloatField(default=None),
        ),
    ]
